language: python
script: pytest
python:
    - "3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install pylint 
  - pip install black
  - pip install -r requirements.txt
script:
  - black sat --diff --check
  - black test --diff --check
  - python -m pylint sat test test_integration --rcfile conf/.pylintrc
  - pytest --cov=. --cov-config=conf/.coveragerc -m "not integration"
after_success:
  - coveralls