language: python

python: 
- 3.6

matrix:
    include:
        - os: linux
          python: 3.6
        - os: osx
          language: generic
          env: INSTALL_TYPE=macpython P_VERSION=3.6 VENV=venv

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    git clone https://github.com/MacPython/terryfy.git
    # Avoid printing the lines from the script below.
    source terryfy/travis_tools.sh
    get_python_environment $INSTALL_TYPE $P_VERSION $VENV
  fi
install:
  - pip install -U pip
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  #- pip install flake8
  #- pip install pylint 
  # Project specific dependencies
  - pip install -r requirements.txt
script:
  - pytest --cov=sat
  #- python -m flake8
  #- python -m pylint sat/sat sat/comp sat/report sat/changes sat/deps sat/app sat/test
after_success:
  - coveralls